### ISSUE TITLE
French translation files

### ISSUE THREAD

**Issue by QuentiumYT** [sw2719/steam-account-switcher#18]
Hello,

I found you github repo and I decided to translate the software in French so I did it.
I can't create a new pull request or upload files so I forked your repo and I'm uploading the files in here as well.

[steamswitcher.zip](https://github.com/sw2719/steam-account-switcher/files/4351070/steamswitcher.zip)

Hope you will add them, and if possible, make pull requests open :)

Have a nice day/evening.

**Comment by sw2719** [comment]
I totally did not expect something like this! It's gonna take a while because of tightly designed UI. Button sizes and window sizes will have to be adjusted. Hopefully I could add them soon. But anyway, thanks for french translation!
And about the PR part.. I really don't know how to make PRs open. Isn't it open already?

**Comment by QuentiumYT** [comment]
Haha, I like this project because switching for me was always annoying. I saw some UI sizes so i managed to reduce french translated words to acronyms or remove some other words.

I don't know a lot about GitHub but managed to create a PR with a new branch and submit it :D

**Comment by sw2719** [comment]
@QuentiumYT I thought a lot about this but uhh.. I think there's no way than this. I have been using some translators to manage French translation. Update 2.4 is almost ready but since a lot of things has been changed, I can't really update French translation. If you could provide a new translation and check for any error, that would be great. If you are up for it, you can clone the update_2.4 branch and edit fr_FR steamswitcher.po file. Please let me know.

**Comment by QuentiumYT** [comment]
Hello, yes I can do it again for the new update, I'm just in vacations so I'm not sure if I have the time to do it but when I will be back home there's no problem :)

**Comment by sw2719** [comment]
OK, take your time and let me know when you start working on it. Various UI problems might rise so I will test it and leave feedback here. Maybe those issues could be fixed without modifying the UI sizes.

**Comment by sw2719** [comment]
I have merged the PR. From my testing, there are clearly some issues especially in initial setup which was totally remade. I know little about the French language so.... can you test it and let me know how could I fix the UI problems without modifying the UI too much? I could modify stuffs like line endings. Clone the update_2.4 branch and install the dependencies using requirements.txt. You can test stuffs like update dialog and initial setup using Debug menu.

From my testing, these parts have issues:
* Main menu (Restart Steam & Exit button)
  - Could skip the 'Restart' part in French. I had plans to iconify the buttons, but it was not in my priority. Maybe I could do it now, though it might take hell lot of time.
* About window (which is stretched at the moment)
  - Horizontally stretched UI looks really weird. How could it be improved?
* Initial setup 
  - Labels are too long. Could use some newlines and stretch the window vertically. Vertically long UI is better than horizantally long imo.)

Also, I had issues merging PR since your fork was based on the master branch. Would deleting fork repo and re-forking work? I don't really fork repos so I have no idea.

Lastly, if you've got any feedback or suggestions to the new update, that would be great as well.

**Comment by QuentiumYT** [comment]
I changed the translations and explained everything in the PR #33.
I never had to contribute twice to the same project and I didn't knew how to do so.
Everything was kinda messy and I apologise for that. I've created a new branch on my fork now haha.
I really like the new update, it's so much cleaner than the previous one!

I don't have that much things to say because I don't wanna change your code ^^ but:
- You can add the icon of every other window
- The width of the main window and account order window need a few more pixels
- Add the key listener ESC on every window to close them easily
`self.top.bind("<Escape>", lambda event: self.close())`
- If you need translations for the debug menu, I can add them as well

You have done an awesome work and I keep follow your updates haha tell me if you need anything else!

**Comment by sw2719** [comment]
OK, I'm checking it right now. By the way:

The width of the main window and account order window need a few more pixels

Tell me more about this since I didn't see any problems. Can you post images or describe problems more precisely?

**Comment by QuentiumYT** [comment]
By that, I mean with the french translation
![Main window](https://user-images.githubusercontent.com/35229942/88340813-c7ada800-cd3c-11ea-841c-417607f0237b.png)
![Account window](https://user-images.githubusercontent.com/35229942/88340816-c8463e80-cd3c-11ea-8782-2c109d1ede4e.png)
I can't lower then lenght or anything so yeah, a letter or less is missing 😅

**Comment by sw2719** [comment]
![main](https://user-images.githubusercontent.com/22590718/88343529-92c14580-cd7c-11ea-93fb-4c07c0e1637c.PNG)
![ord](https://user-images.githubusercontent.com/22590718/88343538-948b0900-cd7c-11ea-8f37-e8af55da2d74.PNG)

Huh, that is not happening on my end. Looks like padding is all messed up on your end. Don't know why. Will investigate this.

**Comment by sw2719** [comment]
![mainw](https://user-images.githubusercontent.com/22590718/88343678-e7fd5700-cd7c-11ea-92ad-fb6f95ac94c8.PNG)
![ord](https://user-images.githubusercontent.com/22590718/88343538-948b0900-cd7c-11ea-8f37-e8af55da2d74.PNG)

Huh, that is not happening on my end. Looking at your pics, looks like padding is all messed up. Don't know why. Will investigate this. Does that also happen when you use version 2.3.3 executable release?

Also, the items in debug menu are not intended to be translated ;) Normal users won't even see them anyway.

**Comment by sw2719** [comment]
OK, I pushed a few commits which might fix those issues. Could you test again?
By the way, translation for 'Failed checking for updates. Click here to try again.' is too long. Test it via Debug > Check for updates (Raise error)

**Comment by QuentiumYT** [comment]
Sorry for the delay but no, that doesn't change anything, I tested with the new commits, with Python 32bits.
![Element lenght](https://user-images.githubusercontent.com/35229942/88475085-02763280-cf2d-11ea-801f-b245ca958fe7.png)
This is very weird, I haven't done anything special, I'm using Python 3.8.1 but I'm not sure if it's the issue.
And I guess you fixed the translation for 'Failed checking for updates. Click here to try again.' :)

And when I try testing with the latest executable, it's missing pget library :( 
![Pget module](https://user-images.githubusercontent.com/35229942/88475327-1ae74c80-cf2f-11ea-8e23-05e732c71b13.png)

**Comment by QuentiumYT** [comment]
I saw that even the english version 
![image](https://user-images.githubusercontent.com/35229942/88475544-220f5a00-cf31-11ea-8338-2e58e7159478.png)
was kinda stretched. The korean one is fine (except now with the new 20px wider) 
![image](https://user-images.githubusercontent.com/35229942/88475556-4ff49e80-cf31-11ea-993e-fb4f3a8bca08.png)

With the constant size of 17 | 7 | 22 for each element, it will fit with every language now :D

I won't create a new pull request for this little adjustement but that should be working fine now :)

**Comment by sw2719** [comment]
I've applied width of 16 5 22 since 17 7 22 looked weird on my screen. Also v2.3.3 doesn't require pget. Did you make executable of 2.4 yourself?

**Comment by QuentiumYT** [comment]
Uhm no 🤔 I ran the executable inside the same directory as the 2.4 so it used the latest imports.
Anyway, this looks still kinda broken :( idk why we have a different view but whatever.
![image](https://user-images.githubusercontent.com/35229942/88477814-6c99d200-cf43-11ea-96de-d9b52636f3df.png)

**Comment by sw2719** [comment]
[Here's a v2.4 Executable with console.](http://sw2719.synology.me/exe.win-amd64-3.7.zip)
Could you try with this one? I really don't know why that's happening. I use Python 3.7.7 64-bit.

**Comment by QuentiumYT** [comment]
I still got the padding issue 
![image](https://user-images.githubusercontent.com/35229942/88478379-08c5d800-cf48-11ea-9515-caba04a88dc9.png)
Looks better but the "Quit" button is still too small.

**Comment by sw2719** [comment]
You can download another build using the link I provided above. I'm really sorry to bother you with these tests but at the same time I really want to solve your problem.

**Comment by QuentiumYT** [comment]
The build you provided doesn't change anything, it's almost exaclty the same so it should be larger (except if it does fit on your screen) or changing the way the buttons are disposed. For example using grid but that will be not the right thing to do. I will look for any solution I can find.

**Comment by sw2719** [comment]
Can you experiment with the button sizes? I've sent the build to a couple of friends of mine and they had no issue.

![example](https://user-images.githubusercontent.com/22590718/88521082-6719b600-d02f-11ea-8cc0-28109679b004.PNG)
Looks like this on my screen.

**Comment by QuentiumYT** [comment]
I already tried this build, I changed the windows size, the font is the regular one and latest windows version. It might be due to the default language set to Korean on your/friends computer. But except changing the button size, there's nothing to do else :(

**Comment by sw2719** [comment]
Yeah try changing button sizes yourself, and tell me which sizes work for you.

```py
        button_toggle = ttk.Button(self.bottomframe,
                                   width=15,
                                   text=_('Toggle auto-login'),
                                   command=toggleAutologin)

        button_quit = ttk.Button(self.bottomframe,
                                 width=6,
                                 text=_('Exit'),
                                 command=self.quit)

        button_restart = ttk.Button(self.bottomframe,
                                    width=23,
                                    textvariable=self.restartbutton_text,
                                    command=self.exit_after_restart)

        button_toggle.pack(side='left', padx=3, pady=3)
        button_quit.pack(side='left', pady=3)
        button_restart.pack(side='right', padx=3, pady=3)
```

These are the sizes that I use and works for me.
Also, I noticed that the font is slightly different. I could try my app on a VM or something. I'll keep you posted.

**Comment by sw2719** [comment]
![problem](https://user-images.githubusercontent.com/22590718/88740299-bf5bcf80-d177-11ea-8658-f8afb6dfdbaa.PNG)

Buttons look weird in English Windows indeed. I will try to fix it.

**Comment by sw2719** [comment]
Alright, could you test the update_2.4 branch again? You'd have to download dependencies again since there were changes in dependency. I've pushed several commits to address the issue.

**Comment by QuentiumYT** [comment]
Yeah this is fine! It was the OS locale that was messing with the app. Everything is good now :)
One more thing is the about window, it's larger in french so it needs to be centered again:
`aboutwindow.geometry("%sx180+520+350" % width)` [line 608](https://github.com/sw2719/steam-account-switcher/blob/update_2.4/modules/main.py#L608)
(I won't create a messy pull request for this change haha)
Great work!

**Comment by sw2719** [comment]
I changed the warning in French to be 3 lines for cleaner (less-stretched-looking) UI.

**Comment by sw2719** [comment]
How can I contact you without re-opening this issue for later translations?

**Comment by QuentiumYT** [comment]
You can open a new issue but for small translations, feel free to send me some messages on Discord `QuentiumYT#0207` :)

**Comment by sw2719** [comment]
Alright. Thanks for all this help. Really appreciate it. I can fianlly close this issue now.
