### ISSUE TITLE
Avatar update freeze (asyncio)

### ISSUE THREAD

**Issue by QuentiumYT** [sw2719/steam-account-switcher#36]
I found this problem while updating the avatar icon
![Error](https://user-images.githubusercontent.com/35229942/90555162-398bdc80-e197-11ea-8442-14a3bf76fe15.png)

It's because of Python 3.6 asyncio library which doesn't know the run method (new only in Python 3.7).
https://docs.python.org/3.7/library/asyncio-task.html#asyncio.run

For a fix, you could do an `await main()` instead of using asyncio :)

**Comment by sw2719** [comment]
Actually, things like create_task() are new in 3.7 as well. Just use Python 3.7 or higher, or use exe instead. asyncio was hugely changed in 3.7 and it would take low-readability-low-level code to support pre-3.7.

Also, it’s not simple as that. asyncio.run is used for calling async function inside a synchronous function. You can’t use await in a synchronous function.

Sure, I’m able to support Python 3.6 after all. But given that I wrote this code to be primarily used as executable bundled with cx_freeze, supporting old versions of Python doesn’t seem necessary.

**Comment by QuentiumYT** [comment]
Well, I won't update until Python 3.9 so for now this projet is just broken for me :(

I haven't seen the error alongside the code but I understand now and you're right, I found a method to do an await in a synchronous function but it's not the right way ¯\_(ツ)_/¯

Anyway, I will use an older version of your software.

**Comment by sw2719** [comment]
Well you could replace
```
    async def main():
        tasks = [asyncio.create_task(download_image(steamid)) for steamid in steamid_list]
        await asyncio.gather(*tasks)

    asyncio.run(main())
```
with this:
```
    async def main():
        futures = [asyncio.ensure_future(download_image(steamid)) for steamid in steamid_list]
        await asyncio.gather(*futures)

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```
This will work on 3.5 and 3.6.

**Comment by QuentiumYT** [comment]
Yes this is the same as I did with an other project but anyway, I'll wait for Python 3.9.

**Comment by sw2719** [comment]
@QuentiumYT For your information, as of v2.5 (specifically, as of commit df313a5), Python 3.5~3.6 should be compatible now.

**Comment by QuentiumYT** [comment]
Oh nice, one thing, I finally upgraded my Python version to 3.8.6 haha 😅
