### ISSUE TITLE
Update Avatar fails to show the avatar

### ISSUE THREAD

**Issue by OmegaPaladin** [sw2719/steam-account-switcher#46]
While the core functionality of the account switcher works great, either clicking on "Update all avatars" or clicking on individual accounts to update the avatar both show signs of processing a command, but do not actually make changes.  I still see N/A for both my accounts.

Both accounts have avatars visible in steam and in browser.

**Comment by sw2719** [comment]
Since I can't reproduce this issue, I would need some more information. Is there an 'avatar' folder in your program directory? If so, are there all avatar files in the folder?

**Comment by OmegaPaladin** [comment]
There is an avatar folder.  No files are present in that directory.  I tried enabling and disabling the show avatars feature and it did nothing.

**Comment by sw2719** [comment]
OK Could you please try these:

Create a shortcut of the program and add '-logfile' at the end of target.
It should look like this: ```"...\[Program Directory]\Steam Account Switcher.exe" -logfile```
Run the program with the shortcut, try updating avatars, and exit the program.
A log should be created in the program directory. Please share the contents of the log file.

**Comment by OmegaPaladin** [comment]
OK, this was crazy.  I launched the program with the shortcut to create the logfile, and the avatars successfully updated!  All previous times I used a shortcut on my desktop created when I installed the program, but there were no parameters or switches in the shortcut on my desktop.

I have no idea what that changed.  Here is the logfile, just for reference.

``` Listing current config...
locale: en_US
autoexit: false
mode: normal
try_soft_shutdown: true
show_avatar: true
steam_path: reg
Checking registry...
AutoLoginUser: omegapaladin144
RememberPassword: 1
SteamExe: c:/program files (x86)/steam/steam.exe
SteamPath: c:/program files (x86)/steam
pid: 15040
ActiveUser: 89473849
Checking Steam.exe location...
Steam located at c:/program files (x86)/steam
Init complete.
Update check start
Server version is 2.6.1
Client version is 2.6.1
On latest version
Found image URL for 76561198049739577
Found image URL for 76561199143511338
Downloading https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/88/88d658cb87344421d07063698ab274d7841a49b0_full.jpg for 76561198049739577...
Downloading https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/bc/bc20445f4bc2a1c8475b8324933d7c1ba258eb24_full.jpg for 76561199143511338...
Menu refreshed with 2 account(s)
```

**Comment by sw2719** [comment]
Well that's both a good news and a bad news. Good news is that it worked (somehow) and the bad news is that I have no idea how that worked. Well if you encounter any other problems, feel free to reopen the issue or create a new one.
