### ISSUE TITLE
[BUG] Registry Error

### ISSUE THREAD

**Issue by toper22850** [sw2719/steam-account-switcher#48]
**Describe the bug**
after installing windows 11, I downloaded the steam account switcher, when I open this error, steam is installed and visual c++ too

**To Reproduce**

**Expected behavior**

**Screenshots**
https://imgur.com/a/m7m6fr3
**Environment**
 - OS: [e.g. Windows 11 x64]
 - Program Version [e.g. 2.6.1]

**Additional context**

**Comment by sw2719** [comment]
Can you open registry editor and check if HKEY_CURRENT_USER\Software\Valve\Steam exists?
I can't reproduce this issue so you have to help me investigate. Thanks.

**Comment by toper22850** [comment]
![image](https://user-images.githubusercontent.com/65308193/171660618-ced95235-2157-4019-830b-4560025ff8f8.png)

**Comment by sw2719** [comment]
Thanks. Identified the issue and currently looking for a fix.

**Comment by sw2719** [comment]
Check #49 for updates on this issue.

**Comment by sw2719** [comment]
Should be fixed in v2.7. Please reopen unless resolved.

**Comment by toper22850** [comment]
Thanks, It works
