### ISSUE TITLE
[BUG] Update all avatars

### ISSUE THREAD

**Issue by japanese-xevvo** [sw2719/steam-account-switcher#51]
1. Go to 'Menu'
2. Click on 'Update all avatars'
3. See error

**Screenshots**
![изображение](https://user-images.githubusercontent.com/77848119/172463480-5ea55516-d3ce-401d-925d-507959bbf18d.png)

**Environment**
 - OS: Windows 10 x64 21H2 19044.1706
 - Program Version 2.7

**Comment by sw2719** [comment]
Found the issue and will be fixed in 2.7.1. Thanks for reporting.
