### ISSUE TITLE
[BUG] Using win11 dark theme makes text invisible

### ISSUE THREAD

**Issue by FluffyDiscord** [sw2719/steam-account-switcher#53]
**Describe the bug**
Using custom windows 11 dark theme makes the text invisible as the theme has dark background and white text color.

**To Reproduce**
1. Open the program

**Expected behavior**
Program background and text colors should use windows colors by default - or add option to set our own colors

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/10332247/174432986-d2664a43-f0eb-47a2-bd26-5fd955f91850.jpg)

**Environment**
 - OS: Win 11 Pro 22000.675
 - Program Version: 2.7.1

**Comment by sw2719** [comment]
Which theme are you using? I probably need to test it myself to fix it.

**Comment by FluffyDiscord** [comment]
hey, sorry for the late response, here it is

[BIB3 WIN theme.zip](https://github.com/sw2719/steam-account-switcher/files/8986064/BIB3.WIN.zip) (source page [here](https://www.deviantart.com/niivu/art/BIB3-for-Windows-886441919))

you can apply it using the https://github.com/namazso/SecureUxTheme

**Comment by sw2719** [comment]
Will look into it.

**Comment by sw2719** [comment]
New version is out and should fix the problem. Please let me know if it works. Thank you for your patience!
