### ISSUE TITLE
[REQUEST] check if account has vacban

### ISSUE THREAD

**Issue by j4ck3** [sw2719/steam-account-switcher#58]
**Describe the solution you'd like**
On the account list, a icon showing if the account has a vacban. 

**Additional context**
Sometimes I play hvh and it would be nice to see if the account is banned before I login.

![example](https://user-images.githubusercontent.com/94866858/210555151-25366225-d3e2-4c1c-a863-4a5ef98b6520.png)

**Comment by sw2719** [comment]
Sorry, but I would have to turn down this one.
I won’t implement a feature that only benefits cheaters. Sure, cheaters could use my program to cheat on multiple accounts, but this program  is NOT ‘made for cheaters’.
