### ISSUE TITLE
[BUG] no start program

### ISSUE THREAD

**Issue by yuliitezary** [sw2719/steam-account-switcher#63]
![image](https://github.com/sw2719/steam-account-switcher/assets/94526027/036ed937-d142-47c7-895b-644f9e0b18e5)

**Comment by sw2719** [comment]
Please post your loginusers.vdf since I can't reproduce this issue.

It's located in the config folder in your Steam installation directory and looks like this:
```
"users"
{
	"[YOUR_STEAMID64]"
	{
		"AccountName"		"[YOUR_ACCOUNT_NAME]"
		"PersonaName"		"[YOUR_PROFILE_NAME]"
		"RememberPassword"		"1"
		"WantsOfflineMode"		"0"
		"SkipOfflineModeWarning"		"0"
		"AllowAutoLogin"		"1"
		"MostRecent"		"1"
		"Timestamp"		"1691459620"
	}
        ...
}
```

Please censor your SteamID, username and profile name if you don't want them to be publicly visible.
